# Generated by Django 3.0.4 on 2020-03-25 21:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0002_auto_20200325_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='555-555-5555', max_length=128, region=None),
        ),
    ]
