# Generated by Django 3.0.4 on 2020-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0004_confirmationtoken_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationtoken',
            name='email',
            field=models.EmailField(default='livelyhood.tech@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
