# Generated by Django 3.0.4 on 2020-04-08 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0005_auto_20200331_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(default='555-555-5555', max_length=128, region=None)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('contact_preference', models.PositiveSmallIntegerField(choices=[(1, 'sms'), (2, 'call')], default=1)),
            ],
        ),
    ]
