# Generated by Django 3.0.4 on 2020-04-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0005_auto_20200331_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requestor',
        ),
    ]
