# Generated by Django 3.0.4 on 2020-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0007_errand_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='requestor_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
