# Generated by Django 3.0.4 on 2020-04-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0008_errand_requestor_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
