# Generated by Django 3.0.4 on 2020-04-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0008_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errand',
            name='request_round',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
