# Generated by Django 3.0.4 on 2020-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0009_auto_20200423_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='errand',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
