# Generated by Django 3.0.4 on 2020-07-16 15:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0010_errand_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('token', models.CharField(default='569694', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfirmationToken',
        ),
        migrations.AddField(
            model_name='errand',
            name='access_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
