# Generated by Django 3.0.4 on 2020-07-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0011_auto_20200716_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='address_str',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='apt_no',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token',
            field=models.CharField(default='035042', max_length=6),
        ),
    ]
