# Generated by Django 3.0.4 on 2020-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0013_auto_20200717_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='token',
            field=models.CharField(default='398946', max_length=6),
        ),
    ]
