# Generated by Django 3.0.4 on 2020-07-31 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from datetime import timedelta

def convert_errand_urgency_to_deadline_datetime(apps, schema_editor):
    days_to_add = {
        1: 1,
        2: 3
    }

    Errand = apps.get_model('errand_matcher', 'Errand')
    
    for e in Errand.objects.all():
        e.due_by = e.requested_time + timedelta(days=days_to_add[e.urgency])
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0014_auto_20200725_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='errand',
            name='requestor_review',
        ),
        migrations.AddField(
            model_name='errand',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 15, 32, 36, 383151, tzinfo=utc)),
        ),
        migrations.RunPython(convert_errand_urgency_to_deadline_datetime),
        migrations.RemoveField(
            model_name='errand',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='errand',
            name='volunteer_review',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_request_rounds',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='errand',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'submitted'), (1, 'open'), (2, 'in progress'), (3, 'complete'), (4, 'failed')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'volunteer'), (2, 'requestor'), (3, 'partner')], default=1),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token',
            field=models.CharField(default='055954', max_length=6),
        ),
        migrations.AddField(
            model_name='errand',
            name='affiliated_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_partner', to='errand_matcher.Partner'),
        ),
    ]
