# Generated by Django 3.0.4 on 2020-08-05 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('errand_matcher', '0015_auto_20200731_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestor',
            name='contact_preference',
        ),
        migrations.RemoveField(
            model_name='requestor',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='requestor',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='errand',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 18, 23, 31, 15933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='token',
            field=models.CharField(default='125535', max_length=6),
        ),
    ]
